name: Publish to Chrome Web Store

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Zip the extension
      run: zip -r extension.zip . -x ".git/*" ".github/*" ".gitattributes" "README.md" "TODO.md" "icons/icon.ai"

    - name: Upload to Chrome Web Store
      uses: mobilefirstllc/cws-publish@latest
      with:
        action: 'publish'
        client_id: ${{ secrets.CLIENT_ID }}
        client_secret: ${{ secrets.CLIENT_SECRET }}
        refresh_token: ${{ secrets.REFRESH_TOKEN }}
        extension_id: ${{ secrets.EXTENSION_ID }}
        zip_file: 'extension.zip'
